version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    groups:
      github-actions:
        patterns:
          - "*"
  # Python
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    groups:
      python-minor-patch:
        update-types:
          - minor
          - patch
