# Generated by Django 5.0.14 on 2026-09-28 06:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ESignTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("module", models.CharField(max_length=64)),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ORDER", "Order"),
                            ("JUDGEMENT", "Judgement"),
                            ("SUMMONS", "Summons"),
                            ("NOTICE", "Notice"),
                            ("WARRANT", "Warrant"),
                            ("VAKALATNAMA", "Vakalatnama"),
                            ("APPLICATION", "Application"),
                            ("CASE_FILING", "Case filing"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("provider", models.CharField(max_length=32)),
                ("provider_transaction_id", models.CharField(blank=True, max_length=128)),
                ("source_file_id", models.CharField(max_length=64)),
                ("placeholder_file_id", models.CharField(blank=True, max_length=64)),
                ("signed_file_id", models.CharField(blank=True, max_length=64)),
                ("sign_placeholder", models.JSONField(blank=True, default=dict)),
                ("document_hash", models.CharField(blank=True, max_length=128)),
                ("signature_field_name", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SIGNING", "Signing"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=1)),
                ("request_audit", models.JSONField(blank=True, default=dict)),
                ("response_audit", models.JSONField(blank=True, default=dict)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("failure_message", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField()),
                ("callback_received_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retry_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retries",
                        to="esign.esigntransaction",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="esign_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "eSign Transaction",
                "verbose_name_plural": "eSign Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "expires_at"], name="esign_status_expires_idx"),
                    models.Index(fields=["entity_type", "entity_id"], name="esign_entity_idx"),
                    models.Index(
                        fields=["organization_id", "created_at"], name="esign_org_created_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="esigntransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_transaction_id", ""), _negated=True),
                fields=("provider", "provider_transaction_id"),
                name="esign_unique_provider_transaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="esigntransaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "SUCCESS"), _negated=True),
                    models.Q(("signed_file_id", ""), _negated=True),
                    _connector="OR",
                ),
                name="esign_success_requires_signed_file",
            ),
        ),
        migrations.AddConstraint(
            model_name="esigntransaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "SIGNING"), _negated=True),
                    models.Q(("placeholder_file_id", ""), _negated=True),
                    _connector="OR",
                ),
                name="esign_signing_requires_placeholder",
            ),
        ),
    ]
