# Generated by Django 5.0.14 on 2026-09-08 11:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiVersionChangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("additional_attributes", models.JSONField(blank=True, default=dict)),
                ("version", models.CharField(max_length=50)),
                ("change_log", models.TextField()),
            ],
            options={
                "verbose_name": "API Version Change Log",
                "verbose_name_plural": "API Version Change Logs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AdditionalAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("integer", "integer"),
                            ("float", "float"),
                            ("number", "number"),
                            ("character", "character"),
                            ("boolean", "boolean"),
                            ("datetime", "datetime"),
                            ("date", "date"),
                            ("json", "json"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_nullable", models.BooleanField(default=True)),
                ("default_value", models.JSONField(blank=True, default=None, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_attributes",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Additional Attribute",
                "verbose_name_plural": "Additional Attributes",
                "ordering": ("-created_at",),
                "unique_together": {("content_type", "name")},
            },
        ),
    ]
