# Generated by Django 5.0.14 on 2026-09-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiversionchangelog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
