# Generated by Django 5.0.14 on 2026-09-17 22:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("additional_attributes", models.JSONField(blank=True, default=dict)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("supreme_court", "Supreme Court"),
                            ("high_court", "High Court"),
                            ("district_court", "District Court"),
                            ("session_court", "Session Court"),
                            ("magistrate_court", "Magistrate Court"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "jurisdictions",
                    models.ManyToManyField(
                        blank=True, related_name="organizations", to="locations.location"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
