"""PDF service models: versioned template configuration and generation jobs.

Configuration lives in the database (spec 0016 #2.1) so new document types can
be added without a deployment. Jobs (#2.2) and their bulk chunks (#2.3) record
what was generated; the generated bytes themselves live in ``apps.files`` and
only the returned ``file_id`` values are kept here.
"""

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.db import models, transaction
from django.db.models import Max
from django.utils import timezone

from apps.core.models import BaseActivatableModel, BaseModel

from .exceptions import PDFJobStateError

template_key_validator = RegexValidator(
    regex=r"^[a-z0-9][a-z0-9_-]*$",
    message="Use lowercase letters, digits, hyphens and underscores (e.g. case-summons).",
)


class PDFTemplate(BaseModel, BaseActivatableModel):
    """A document type callers request by its stable ``key``."""

    key = models.CharField(max_length=100, unique=True, validators=[template_key_validator])
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    class Meta(BaseModel.Meta):
        """Meta options."""

        ordering = ("key",)

    def __str__(self):
        return self.key


class PDFTemplateVersion(BaseModel):
    """One immutable revision of a template's format and data configuration.

    Editing a configuration means creating a new version. A version that a job
    has already used can no longer change, so every job keeps describing what
    was actually rendered. At most one version per template is active, and
    saving an active version deactivates its siblings.
    """

    template = models.ForeignKey(PDFTemplate, on_delete=models.CASCADE, related_name="versions")
    version = models.PositiveIntegerField(blank=True)
    format_config = models.JSONField(default=dict)
    data_config = models.JSONField(default=dict, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta(BaseModel.Meta):
        """Meta options."""

        ordering = ("template", "-version")
        constraints = [
            models.UniqueConstraint(
                fields=["template", "version"],
                name="pdf_template_version_unique",
            ),
            models.UniqueConstraint(
                fields=["template"],
                condition=models.Q(is_active=True),
                name="pdf_template_single_active_version",
            ),
        ]

    def __str__(self):
        return f"{self.template_id and self.template.key} v{self.version}"

    def clean(self):
        """Validate both configurations at authoring time (#9)."""
        from .services.validation import validate_data_config, validate_format_config

        super().clean()
        errors = {}
        for field, validator in (
            ("format_config", validate_format_config),
            ("data_config", validate_data_config),
        ):
            try:
                validator(getattr(self, field))
            except ValidationError as exc:
                errors[field] = exc.messages
        if errors:
            raise ValidationError(errors)
        self._ensure_unused_configuration_unchanged()

    def _ensure_unused_configuration_unchanged(self):
        """Reject edits to the configuration of a version a job has used."""
        if self._state.adding or not self.pk:
            return
        stored = (
            PDFTemplateVersion.objects.filter(pk=self.pk)
            .values("format_config", "data_config", "version", "template_id")
            .first()
        )
        if stored is None:
            return
        changed = (
            stored["format_config"] != self.format_config
            or stored["data_config"] != self.data_config
            or stored["version"] != self.version
            or stored["template_id"] != self.template_id
        )
        if changed and self.jobs.exists():
            raise ValidationError(
                "This version has been used to generate documents and cannot be edited; "
                "create a new version instead."
            )

    def save(self, *args, **kwargs):
        """Assign the next version number, validate, and keep one active version."""
        with transaction.atomic():
            if self.version is None:
                latest = PDFTemplateVersion.objects.filter(template_id=self.template_id).aggregate(
                    latest=Max("version")
                )["latest"]
                self.version = (latest or 0) + 1
            # Siblings are deactivated before validation so the single-active
            # constraint check sees the final state; a validation failure rolls
            # the deactivation back with the rest of the transaction.
            if self.is_active:
                PDFTemplateVersion.objects.filter(
                    template_id=self.template_id, is_active=True
                ).exclude(pk=self.pk).update(is_active=False, updated_at=timezone.now())
            self.full_clean()
            super().save(*args, **kwargs)


class PDFJobStatus(models.TextChoices):
    """Job lifecycle of spec 0016 #3."""

    CREATED = "CREATED", "Created"
    QUEUED = "QUEUED", "Queued"
    PROCESSING = "PROCESSING", "Processing"
    COMPLETED = "COMPLETED", "Completed"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS", "Partial success"
    FAILED = "FAILED", "Failed"
    CANCELLED = "CANCELLED", "Cancelled"


TERMINAL_JOB_STATUSES = frozenset(
    {
        PDFJobStatus.COMPLETED,
        PDFJobStatus.PARTIAL_SUCCESS,
        PDFJobStatus.FAILED,
        PDFJobStatus.CANCELLED,
    }
)

CANCELLABLE_JOB_STATUSES = frozenset(
    {PDFJobStatus.CREATED, PDFJobStatus.QUEUED, PDFJobStatus.PROCESSING}
)

_JOB_TRANSITIONS = {
    PDFJobStatus.CREATED: {PDFJobStatus.QUEUED, PDFJobStatus.CANCELLED},
    PDFJobStatus.QUEUED: {PDFJobStatus.PROCESSING, PDFJobStatus.CANCELLED},
    PDFJobStatus.PROCESSING: {
        PDFJobStatus.COMPLETED,
        PDFJobStatus.PARTIAL_SUCCESS,
        PDFJobStatus.FAILED,
        PDFJobStatus.CANCELLED,
    },
}


class PDFJob(BaseModel):
    """One request to generate a document (or a bulk set of documents)."""

    key = models.CharField(max_length=100)
    template_version = models.ForeignKey(
        PDFTemplateVersion, on_delete=models.PROTECT, related_name="jobs"
    )
    tenant_id = models.CharField(max_length=64)
    entity_id = models.CharField(max_length=128, blank=True)
    organization = models.ForeignKey(
        "organizations.Organization",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="pdf_jobs",
    )
    requested_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="pdf_jobs",
    )
    locale = models.CharField(max_length=16, blank=True)
    correlation_id = models.CharField(max_length=128, blank=True)
    status = models.CharField(
        max_length=20, choices=PDFJobStatus.choices, default=PDFJobStatus.CREATED
    )
    is_bulk = models.BooleanField(default=False)
    reuse_key = models.CharField(max_length=64)
    # The caller's payload only: authorization headers and tokens are never
    # captured here (#13), the worker re-acquires credentials from settings.
    request_data = models.JSONField(default=dict, blank=True)
    file_ids = models.JSONField(default=list, blank=True)
    total_count = models.PositiveIntegerField(default=1)
    completed_count = models.PositiveIntegerField(default=0)
    failed_count = models.PositiveIntegerField(default=0)
    attempt_count = models.PositiveSmallIntegerField(default=0)
    error_code = models.CharField(max_length=64, blank=True)
    error_message = models.CharField(max_length=512, blank=True)
    queued_at = models.DateTimeField(null=True, blank=True)
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    files_deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta(BaseModel.Meta):
        """Meta options."""

        indexes = [
            models.Index(fields=["tenant_id", "key", "entity_id"], name="pdf_job_lookup_idx"),
            models.Index(fields=["reuse_key"], name="pdf_job_reuse_key_idx"),
            models.Index(fields=["status"], name="pdf_job_status_idx"),
        ]
        constraints = [
            models.CheckConstraint(
                check=models.Q(status__in=PDFJobStatus.values),
                name="pdf_job_status_valid",
            ),
            models.CheckConstraint(
                check=~models.Q(status=PDFJobStatus.PARTIAL_SUCCESS) | models.Q(is_bulk=True),
                name="pdf_job_partial_success_only_bulk",
            ),
        ]

    def __str__(self):
        return f"{self.key} ({self.status})"

    @property
    def is_terminal(self) -> bool:
        """Whether the job has reached a final status."""
        return self.status in TERMINAL_JOB_STATUSES

    def transition_to(self, status: str) -> None:
        """Move to ``status`` or raise ``PDFJobStateError``.

        Only updates the in-memory instance and its lifecycle timestamps; the
        caller saves (normally under ``select_for_update``).
        """
        allowed = _JOB_TRANSITIONS.get(self.status, set())
        if status not in allowed:
            raise PDFJobStateError(f"A job cannot move from {self.status} to {status}.")
        if status == PDFJobStatus.PARTIAL_SUCCESS and not (self.is_bulk and self.total_count > 1):
            raise PDFJobStateError(
                "Only bulk jobs with more than one record can partially succeed."
            )

        now = timezone.now()
        self.status = status
        if status == PDFJobStatus.QUEUED:
            self.queued_at = now
        elif status == PDFJobStatus.PROCESSING:
            self.started_at = self.started_at or now
        else:
            self.completed_at = now


class PDFJobRecordStatus(models.TextChoices):
    """Lifecycle of one bulk chunk."""

    PENDING = "PENDING", "Pending"
    QUEUED = "QUEUED", "Queued"
    PROCESSING = "PROCESSING", "Processing"
    COMPLETED = "COMPLETED", "Completed"
    FAILED = "FAILED", "Failed"
    CANCELLED = "CANCELLED", "Cancelled"


TERMINAL_RECORD_STATUSES = frozenset(
    {PDFJobRecordStatus.COMPLETED, PDFJobRecordStatus.FAILED, PDFJobRecordStatus.CANCELLED}
)


class PDFJobRecord(BaseModel):
    """One chunk of a bulk job: records ``[offset, offset + count)`` of the input."""

    job = models.ForeignKey(PDFJob, on_delete=models.CASCADE, related_name="records")
    sequence = models.PositiveIntegerField()
    offset = models.PositiveIntegerField(default=0)
    count = models.PositiveIntegerField(default=0)
    status = models.CharField(
        max_length=20, choices=PDFJobRecordStatus.choices, default=PDFJobRecordStatus.PENDING
    )
    file_id = models.CharField(max_length=64, blank=True)
    attempt_count = models.PositiveSmallIntegerField(default=0)
    error_code = models.CharField(max_length=64, blank=True)
    error_message = models.CharField(max_length=512, blank=True)

    class Meta(BaseModel.Meta):
        """Meta options."""

        ordering = ("job", "sequence")
        constraints = [
            models.UniqueConstraint(fields=["job", "sequence"], name="pdf_job_record_unique_seq"),
            models.CheckConstraint(
                check=models.Q(status__in=PDFJobRecordStatus.values),
                name="pdf_job_record_status_valid",
            ),
        ]

    def __str__(self):
        return f"{self.job_id} #{self.sequence} ({self.status})"

    @property
    def is_terminal(self) -> bool:
        """Whether the chunk has reached a final status."""
        return self.status in TERMINAL_RECORD_STATUSES
