# Generated by Django 5.0.14 on 2026-09-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("document", "Document"),
                    ("image", "Image"),
                    ("signature", "Signature"),
                    ("digitally_signed", "Digitally signed"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
