# Generated by Django 5.0.14 on 2026-09-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_rename_max_retry_messagelog_max_retries_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("OTP", "OTP"),
                    ("NOTIFICATION", "Notification"),
                    ("TRANSACTION", "Transaction"),
                ],
                default="NOTIFICATION",
                max_length=20,
            ),
        ),
    ]
