# Generated by Django 5.0.14 on 2026-10-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0006_messagelog_created_by_messagelog_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagelog",
            name="correlation_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="messagelog",
            name="provider",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="messagelog",
            name="provider_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="provider_template_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="messagelog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("filtered", "Filtered"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
