# Generated by Django 5.0.14 on 2026-10-06 16:23

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_organization_created_by_organization_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=100)),
                ("tenant_id", models.CharField(max_length=64)),
                ("entity_id", models.CharField(blank=True, max_length=128)),
                ("locale", models.CharField(blank=True, max_length=16)),
                ("correlation_id", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("PARTIAL_SUCCESS", "Partial success"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("is_bulk", models.BooleanField(default=False)),
                ("reuse_key", models.CharField(max_length=64)),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("file_ids", models.JSONField(blank=True, default=list)),
                ("total_count", models.PositiveIntegerField(default=1)),
                ("completed_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.CharField(blank=True, max_length=512)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("files_deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pdf_jobs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pdf_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PDFJobRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("offset", models.PositiveIntegerField(default=0)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("file_id", models.CharField(blank=True, max_length=64)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.CharField(blank=True, max_length=512)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="pdf.pdfjob",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("job", "sequence"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PDFTemplate",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use lowercase letters, digits, hyphens and underscores (e.g. case-summons).",
                                regex="^[a-z0-9][a-z0-9_-]*$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("key",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PDFTemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(blank=True)),
                ("format_config", models.JSONField(default=dict)),
                ("data_config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="pdf.pdftemplate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("template", "-version"),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="pdfjob",
            name="template_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="pdf.pdftemplateversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="pdfjobrecord",
            constraint=models.UniqueConstraint(
                fields=("job", "sequence"), name="pdf_job_record_unique_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="pdfjobrecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "status__in",
                        ["PENDING", "QUEUED", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED"],
                    )
                ),
                name="pdf_job_record_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="pdftemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version"), name="pdf_template_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="pdftemplateversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("template",),
                name="pdf_template_single_active_version",
            ),
        ),
        migrations.AddIndex(
            model_name="pdfjob",
            index=models.Index(fields=["tenant_id", "key", "entity_id"], name="pdf_job_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="pdfjob",
            index=models.Index(fields=["reuse_key"], name="pdf_job_reuse_key_idx"),
        ),
        migrations.AddIndex(
            model_name="pdfjob",
            index=models.Index(fields=["status"], name="pdf_job_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="pdfjob",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "status__in",
                        [
                            "CREATED",
                            "QUEUED",
                            "PROCESSING",
                            "COMPLETED",
                            "PARTIAL_SUCCESS",
                            "FAILED",
                            "CANCELLED",
                        ],
                    )
                ),
                name="pdf_job_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="pdfjob",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "PARTIAL_SUCCESS"), _negated=True),
                    ("is_bulk", True),
                    _connector="OR",
                ),
                name="pdf_job_partial_success_only_bulk",
            ),
        ),
    ]
